#!/bin/sh

## Скрипт, удаляющий все видеофайлы старше определённого периода на сервере видеоархива.

# Version 1.0

# Подключаем общую для всех скриптов библиотеку функций.
. ./functions

#
# Первичные процедуры - создание файла блокировки, запись в лог файл о начале выполнения.
#

lock_on
log_msg "Запущен"

#####

# Основная программа.

Year=`date +%Y`
Month=`date +%m`
Old=`echo "$Month"-"$Age"|bc`

find "$camshare" -type d -name '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'| grep "$outfiles" > $camshare$tmpfile

# В цикле проходим построчно по временному файлу.
for source in `cat "$camshare$tmpfile"` ;

do
    ddate=`echo "$source" | awk -F / '{ print $7 }'`
    Y=`echo $ddate | head -c4`
    M=`echo $ddate | head -c6 | tail -c2`
    D=`echo -n $ddate | tail -c2`

    if [ $Y -eq `date +%Y`  ] ; then
	    if [ "$M" -le "$Old"  ] ; then
		rm -rf $source
	    else
		echo "Имя каталога $source находится в пределах хранимого промежутка ($Age месяца), поэтому пропущен."
	    fi
	else
	    echo "Каталог $source создан не в этом году и требуется его обработка вручную."
	    # TODO : вставить проверку mtime и переименовывать, пока 2010 год не трогаем.
	    echo $source >> $camshare/$Y.log
	    # TODO вставить обработку и процедуру переименования каталога и его содержимого.

    fi
done

#####

# 
# Окончательные процедуры - удаление временного файла, запись в лог-файл, удаление файла блокировки.
#

clear_tmp
log_msg "Завершён"
lock_off
